mod engine;
mod library;

use tauri::{Manager, RunEvent};
use tauri_specta::{Builder, collect_commands};

/// The commands the frontend can call. Their TypeScript bindings in
/// `src/bindings.ts` are regenerated by the `export_bindings` test.
fn commands() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        engine::engine_info,
        engine::list_output_devices,
        engine::open_default_output,
        engine::open_output,
        engine::close_output,
        engine::play_deck,
        engine::pause_deck,
        engine::cue_deck,
        engine::set_deck_gain,
        engine::set_crossfader,
        engine::set_deck_eq,
        engine::sync_deck,
        engine::set_deck_loop,
        engine::audio_snapshot,
        engine::watch_audio,
        library::search_tracks,
        library::import_folder,
        library::load_deck_file,
    ])
}

pub fn run() {
    let commands = commands();
    let self_test = std::env::args().any(|arg| arg == "--self-test");

    tauri::Builder::default()
        .invoke_handler(commands.invoke_handler())
        .setup(move |app| {
            app.manage(engine::Engine::start());
            app.manage(library::LibraryState::open(app.handle())?);
            if self_test {
                engine::spawn_self_test(app.handle().clone());
            }
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building the Waveform desktop app")
        .run(|app, event| {
            if let RunEvent::Exit = event {
                app.state::<engine::Engine>().stop();
            }
        });
}

#[cfg(test)]
mod tests {
    use specta_typescript::Typescript;

    /// Regenerates the frontend's TypeScript bindings. CI fails if the
    /// regenerated file differs from the committed one.
    #[test]
    fn export_bindings() {
        super::commands()
            .export(
                Typescript::default()
                    .header("// Regenerate with: cargo test -p waveform-desktop export_bindings"),
                "../src/bindings.ts",
            )
            .expect("the TypeScript bindings export");
    }
}
