// Regenerate with: cargo test -p waveform-desktop export_bindings
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Versions and health of the app and its audio engine, for the About view. */
	engineInfo: () => __TAURI_INVOKE<EngineInfo>("engine_info"),
	/**  Output devices the host reports. */
	listOutputDevices: () => typedError<OutputDevice[], string>(__TAURI_INVOKE("list_output_devices")),
	/**  Opens the default output and starts the tone decks' callback. */
	openDefaultOutput: () => typedError<null, string>(__TAURI_INVOKE("open_default_output")),
	/**  Opens a named output. */
	openOutput: (name: string) => typedError<null, string>(__TAURI_INVOKE("open_output", { name })),
	/**  Closes the output device. */
	closeOutput: () => typedError<null, string>(__TAURI_INVOKE("close_output")),
	/**  Starts a deck. `deck` is 0 to 3. */
	playDeck: (deck: number) => typedError<null, string>(__TAURI_INVOKE("play_deck", { deck })),
	/**  Pauses a tone deck. */
	pauseDeck: (deck: number) => typedError<null, string>(__TAURI_INVOKE("pause_deck", { deck })),
	/**  Stops a tone deck and returns it to the start. */
	cueDeck: (deck: number) => typedError<null, string>(__TAURI_INVOKE("cue_deck", { deck })),
	/**  Sets a deck's gain in decibels. */
	setDeckGain: (deck: number, decibels: number | null) => typedError<null, string>(__TAURI_INVOKE("set_deck_gain", { deck, decibels })),
	/**  Moves the crossfader. 0 is fully deck A, 1 is fully deck B. */
	setCrossfader: (position: number | null) => typedError<null, string>(__TAURI_INVOKE("set_crossfader", { position })),
	/**  Sets one EQ band. `band` is 0 low, 1 mid, 2 high. */
	setDeckEq: (deck: number, band: number, decibels: number | null) => typedError<null, string>(__TAURI_INVOKE("set_deck_eq", { deck, band, decibels })),
	/**  Matches this deck's pitch to the other deck's tempo. */
	syncDeck: (deck: number) => typedError<null, string>(__TAURI_INVOKE("sync_deck", { deck })),
	/**  Loops a deck between two positions, in seconds. */
	setDeckLoop: (deck: number, start: number | null, end: number | null) => typedError<null, string>(__TAURI_INVOKE("set_deck_loop", { deck, start, end })),
	/**  Tempo, key and length of a loaded deck. */
	deckAnalysis: (deck: number) => typedError<DeckAnalysis, string>(__TAURI_INVOKE("deck_analysis", { deck })),
	/**  Moves a deck to a position in seconds. */
	seekDeck: (deck: number, seconds: number | null) => typedError<null, string>(__TAURI_INVOKE("seek_deck", { deck, seconds })),
	/**  Sets playback rate. 1 is the original tempo. */
	setDeckPitch: (deck: number, pitch: number | null) => typedError<null, string>(__TAURI_INVOKE("set_deck_pitch", { deck, pitch })),
	/**  Stores a hot cue. `slot` is 0 to 7 and `seconds` is the position. */
	setHotCue: (deck: number, slot: number, seconds: number | null) => typedError<null, string>(__TAURI_INVOKE("set_hot_cue", { deck, slot, seconds })),
	/**  Jumps to a stored hot cue. */
	jumpHotCue: (deck: number, slot: number) => typedError<null, string>(__TAURI_INVOKE("jump_hot_cue", { deck, slot })),
	/**  Jumps by a number of beats. Negative values jump backward. */
	beatJump: (deck: number, beats: number | null) => typedError<null, string>(__TAURI_INVOKE("beat_jump", { deck, beats })),
	/**  Sets one effect. `slot` 0 is the filter, 1 the delay, 2 the reverb. `amount` is 0 to 1. */
	setEffect: (deck: number, slot: number, amount: number | null) => typedError<null, string>(__TAURI_INVOKE("set_effect", { deck, slot, amount })),
	/**  Arms or stops the master recording. */
	armRecording: (armed: boolean) => typedError<null, string>(__TAURI_INVOKE("arm_recording", { armed })),
	/**  Plays the built-in sampler pad. */
	triggerSampler: () => typedError<null, string>(__TAURI_INVOKE("trigger_sampler")),
	/**  Linear gain for a device input that is already open. 0 leaves it silent. */
	setInputGain: (gain: number | null) => typedError<null, string>(__TAURI_INVOKE("set_input_gain", { gain })),
	/**  Beat times in seconds. Empty until analysis has a grid. */
	deckBeats: (deck: number) => typedError<(number | null)[], string>(__TAURI_INVOKE("deck_beats", { deck })),
	/**  Writes the armed recording to a wav file. */
	saveRecording: (path: string) => typedError<null, string>(__TAURI_INVOKE("save_recording", { path })),
	/**  The latest engine snapshot. */
	audioSnapshot: () => typedError<AudioSnapshot, string>(__TAURI_INVOKE("audio_snapshot")),
	/**  Streams snapshots until the next call replaces it, or the webview goes away. */
	watchAudio: (channel: Channel<AudioSnapshot>) => __TAURI_INVOKE<void>("watch_audio", { channel }),
	/**  Search titles and artists. Uses a read-only connection so an import can write. */
	searchTracks: (query: string) => typedError<LibraryTrack[], string>(__TAURI_INVOKE("search_tracks", { query })),
	/**  Imports audio files under `folder` on a background thread and reports progress. */
	importFolder: (folder: string, channel: Channel<ImportProgress>) => typedError<null, string>(__TAURI_INVOKE("import_folder", { folder, channel })),
	/**  Loads one file the user named onto a deck, and registers it in the library. */
	loadDeckFile: (deck: number, path: string) => typedError<(number | null)[], string>(__TAURI_INVOKE("load_deck_file", { deck, path })),
	/**  Creates a playlist (`playlist` or `crate`) or a smart playlist (`smart`). */
	createCollection: (name: string, kind: string, minBpm: number | null, maxBpm: number | null, musicalKey: string | null) => typedError<LibraryCollection, string>(__TAURI_INVOKE("create_collection", { name, kind, minBpm, maxBpm, musicalKey })),
	/**  Adds a track to a playlist or crate. */
	addToCollection: (collectionId: number, trackId: number) => typedError<null, string>(__TAURI_INVOKE("add_to_collection", { collectionId, trackId })),
	/**  Lists a playlist, or the tracks a smart playlist matches. */
	collectionTracks: (collectionId: number) => typedError<LibraryTrack[], string>(__TAURI_INVOKE("collection_tracks", { collectionId })),
	/**  Stores a rating from 0 to 5. */
	setTrackRating: (trackId: number, rating: number) => typedError<null, string>(__TAURI_INVOKE("set_track_rating", { trackId, rating })),
	/**  Replaces a track's title and artist in the library and the search index. */
	setTrackMetadata: (trackId: number, title: string, artist: string) => typedError<null, string>(__TAURI_INVOKE("set_track_metadata", { trackId, title, artist })),
	/**  Remembers which command a controller control runs. */
	saveMapping: (control: string, commandId: string) => typedError<null, string>(__TAURI_INVOKE("save_mapping", { control, commandId })),
	/**  Stored controller mappings. */
	listMappings: () => typedError<LibraryMapping[], string>(__TAURI_INVOKE("list_mappings")),
	/**  Parent folders of imported tracks. */
	listFolders: () => typedError<string[], string>(__TAURI_INVOKE("list_folders")),
	/**  Attaches a tag to a track. */
	tagTrack: (trackId: number, tag: string) => typedError<null, string>(__TAURI_INVOKE("tag_track", { trackId, tag })),
	/**  Recently played tracks, newest first. */
	recentPlays: () => typedError<LibraryTrack[], string>(__TAURI_INVOKE("recent_plays")),
	/**
	 *  Downloads Open-Unmix UMX-HQ after the user asks. Not called at startup.
	 *  A weight file is kept only when its SHA-256 matches the manifest.
	 */
	downloadStemModel: () => typedError<string, string>(__TAURI_INVOKE("download_stem_model")),
	/**
	 *  Writes a filter-bank preview of `path` and returns the four wav paths.
	 *  Nothing is downloaded. The notice says this is not a neural separation.
	 */
	prepareStemPreview: (path: string) => typedError<StemPreview, string>(__TAURI_INVOKE("prepare_stem_preview", { path })),
	/**  Audio files named vocals, drums, bass, or other in `directory`. */
	listStemAudio: (directory: string) => typedError<string[], string>(__TAURI_INVOKE("list_stem_audio", { directory })),
	/**  Energy and phrase starts for a tempo the library already knows. */
	trackFilters: (bpm: number | null, durationSeconds: number | null) => __TAURI_INVOKE<TrackFilters>("track_filters", { bpm, durationSeconds }),
	/**  Decodes `path` into a stem slot. The slot sums with the decks, so the full mix can keep playing. */
	loadStemSlot: (slot: number, path: string) => typedError<null, string>(__TAURI_INVOKE("load_stem_slot", { slot, path })),
	/**  Plays or stops one stem slot. `slot` is 0 vocals, 1 drums, 2 bass, 3 other. */
	setStemPlaying: (slot: number, playing: boolean) => typedError<null, string>(__TAURI_INVOKE("set_stem_playing", { slot, playing })),
};

/* Types */
/**  Levels, transport and the open device, as the audio thread last published them. */
export type AudioSnapshot = {
	sampleRate: number,
	bufferSize: number,
	callbackCount: number,
	xrunCount: number,
	droppedCommands: number,
	deckAPositionSeconds: number | null,
	deckBPositionSeconds: number | null,
	deckAGainDb: number | null,
	deckBGainDb: number | null,
	deckALevelDb: number | null,
	deckBLevelDb: number | null,
	masterLevelDb: number | null,
	crossfader: number | null,
	deckAPlaying: boolean,
	deckBPlaying: boolean,
	deviceOpen: boolean,
	deviceName: string,
};

/**  Tempo, key and length of a loaded deck. Sync stays off until a tempo exists. */
export type DeckAnalysis = {
	bpm: number | null,
	musicalKey: string,
	durationSeconds: number | null,
};

/**  Versions and health of the app and its audio engine. */
export type EngineInfo = {
	appVersion: string,
	engineVersion: string,
	/**  Reported by the linked JUCE library itself. */
	juceVersion: string,
	compiler: string,
	buildType: string,
	operatingSystem: string,
	architecture: string,
	tauriVersion: string,
	/**  Null when the system webview's version cannot be read. */
	webviewVersion: string | null,
	messageLoop: MessageLoopStatus,
};

/**  Progress for a folder import. `done` counts files finished, including failures. */
export type ImportProgress = {
	done: number,
	total: number,
	path: string,
	failure: string | null,
};

/**  A playlist, crate, or smart playlist. */
export type LibraryCollection = {
	id: number,
	name: string,
	kind: string,
};

/**  A stored controller mapping. */
export type LibraryMapping = {
	control: string,
	commandId: string,
};

/**  One search hit. Paths are included so the user can load the file they picked. */
export type LibraryTrack = {
	id: number,
	title: string,
	artist: string,
	path: string,
	failure: string | null,
};

/**
 *  Whether JUCE's message loop delivers messages. Device management, timers,
 *  and engine callbacks all depend on it.
 */
export type MessageLoopStatus = { state: "responding"; roundTripMicros: number } | { state: "notResponding"; timeoutMillis: number } | { state: "unavailable"; reason: string };

/**  One output the engine can open. */
export type OutputDevice = {
	typeName: string,
	name: string,
};

/**  One filter-bank preview. The files are wavs the mixer can load. They are not a neural separation. */
export type StemPreview = {
	vocals: string,
	drums: string,
	bass: string,
	other: string,
	notice: string,
};

/**  Energy and 32-beat phrases from tempo alone. Nothing is downloaded. */
export type TrackFilters = {
	energy: string,
	phraseStarts: (number | null)[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

