// Regenerate with: cargo test -p waveform-desktop export_bindings
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Versions and health of the app and its audio engine, for the About view. */
	engineInfo: () => __TAURI_INVOKE<EngineInfo>("engine_info"),
	/**  Output devices the host reports. */
	listOutputDevices: () => typedError<OutputDevice[], string>(__TAURI_INVOKE("list_output_devices")),
	/**  Opens the default output and starts the tone decks' callback. */
	openDefaultOutput: () => typedError<null, string>(__TAURI_INVOKE("open_default_output")),
	/**  Opens a named output. */
	openOutput: (name: string) => typedError<null, string>(__TAURI_INVOKE("open_output", { name })),
	/**  Closes the output device. */
	closeOutput: () => typedError<null, string>(__TAURI_INVOKE("close_output")),
	/**  Starts a tone deck. `deck` is 0 or 1. */
	playDeck: (deck: number) => typedError<null, string>(__TAURI_INVOKE("play_deck", { deck })),
	/**  Pauses a tone deck. */
	pauseDeck: (deck: number) => typedError<null, string>(__TAURI_INVOKE("pause_deck", { deck })),
	/**  Stops a tone deck and returns it to the start. */
	cueDeck: (deck: number) => typedError<null, string>(__TAURI_INVOKE("cue_deck", { deck })),
	/**  Sets a deck's gain in decibels. */
	setDeckGain: (deck: number, decibels: number | null) => typedError<null, string>(__TAURI_INVOKE("set_deck_gain", { deck, decibels })),
	/**  Moves the crossfader. 0 is fully deck A, 1 is fully deck B. */
	setCrossfader: (position: number | null) => typedError<null, string>(__TAURI_INVOKE("set_crossfader", { position })),
	/**  Sets one EQ band. `band` is 0 low, 1 mid, 2 high. */
	setDeckEq: (deck: number, band: number, decibels: number | null) => typedError<null, string>(__TAURI_INVOKE("set_deck_eq", { deck, band, decibels })),
	/**  Matches this deck's pitch to the other deck's tempo. */
	syncDeck: (deck: number) => typedError<null, string>(__TAURI_INVOKE("sync_deck", { deck })),
	/**  Loops a deck between two positions, in seconds. */
	setDeckLoop: (deck: number, start: number | null, end: number | null) => typedError<null, string>(__TAURI_INVOKE("set_deck_loop", { deck, start, end })),
	/**  The latest engine snapshot. */
	audioSnapshot: () => typedError<AudioSnapshot, string>(__TAURI_INVOKE("audio_snapshot")),
	/**  Streams snapshots until the next call replaces it, or the webview goes away. */
	watchAudio: (channel: Channel<AudioSnapshot>) => __TAURI_INVOKE<void>("watch_audio", { channel }),
	/**  Search titles and artists. Uses a read-only connection so an import can write. */
	searchTracks: (query: string) => typedError<LibraryTrack[], string>(__TAURI_INVOKE("search_tracks", { query })),
	/**  Imports audio files under `folder` on a background thread and reports progress. */
	importFolder: (folder: string, channel: Channel<ImportProgress>) => typedError<null, string>(__TAURI_INVOKE("import_folder", { folder, channel })),
	/**  Loads one file the user named onto a deck, and registers it in the library. */
	loadDeckFile: (deck: number, path: string) => typedError<(number | null)[], string>(__TAURI_INVOKE("load_deck_file", { deck, path })),
};

/* Types */
/**  Levels, transport and the open device, as the audio thread last published them. */
export type AudioSnapshot = {
	sampleRate: number,
	bufferSize: number,
	callbackCount: number,
	xrunCount: number,
	droppedCommands: number,
	deckAPositionSeconds: number | null,
	deckBPositionSeconds: number | null,
	deckAGainDb: number | null,
	deckBGainDb: number | null,
	deckALevelDb: number | null,
	deckBLevelDb: number | null,
	masterLevelDb: number | null,
	crossfader: number | null,
	deckAPlaying: boolean,
	deckBPlaying: boolean,
	deviceOpen: boolean,
	deviceName: string,
};

/**  Versions and health of the app and its audio engine. */
export type EngineInfo = {
	appVersion: string,
	engineVersion: string,
	/**  Reported by the linked JUCE library itself. */
	juceVersion: string,
	compiler: string,
	buildType: string,
	operatingSystem: string,
	architecture: string,
	tauriVersion: string,
	/**  Null when the system webview's version cannot be read. */
	webviewVersion: string | null,
	messageLoop: MessageLoopStatus,
};

/**  Progress for a folder import. `done` counts files finished, including failures. */
export type ImportProgress = {
	done: number,
	total: number,
	path: string,
	failure: string | null,
};

/**  One search hit. Paths are included so the user can load the file they picked. */
export type LibraryTrack = {
	id: number,
	title: string,
	artist: string,
	path: string,
	failure: string | null,
};

/**
 *  Whether JUCE's message loop delivers messages. Device management, timers,
 *  and engine callbacks all depend on it.
 */
export type MessageLoopStatus = { state: "responding"; roundTripMicros: number } | { state: "notResponding"; timeoutMillis: number } | { state: "unavailable"; reason: string };

/**  One output the engine can open. */
export type OutputDevice = {
	typeName: string,
	name: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

