// Regenerate with: cargo test -p waveform-desktop export_bindings
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Versions and health of the app and its audio engine, for the About view. */
	engineInfo: () => __TAURI_INVOKE<EngineInfo>("engine_info"),
};

/* Types */
/**  Versions and health of the app and its audio engine. */
export type EngineInfo = {
	appVersion: string,
	engineVersion: string,
	/**  Reported by the linked JUCE library itself. */
	juceVersion: string,
	compiler: string,
	buildType: string,
	operatingSystem: string,
	architecture: string,
	tauriVersion: string,
	/**  Null when the system webview's version cannot be read. */
	webviewVersion: string | null,
	messageLoop: MessageLoopStatus,
};

/**
 *  Whether JUCE's message loop delivers messages. Device management, timers,
 *  and engine callbacks all depend on it.
 */
export type MessageLoopStatus = { state: "responding"; roundTripMicros: number } | { state: "notResponding"; timeoutMillis: number } | { state: "unavailable"; reason: string };

